---
abstract: 'Simple Diffing of DBIC Schemas'
author:
  - 'Henry Van Styn <vanstyn@cpan.org>'
build_requires:
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
  aliased: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-Diff
requires:
  Array::Diff: 0
  Data::Dumper::Concise: 0
  Hash::Layout: 0
  JSON: 0
  List::MoreUtils: 0
  List::Util: 0
  Module::Runtime: 0
  Moo: 0
  Moo::Role: 0
  Path::Class: 0
  Scalar::Util: 0
  Try::Tiny: 0
  Types::Standard: 0
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/vanstyn/DBIx-Class-Schema-Diff.git
version: 1.00
